server:
  port: 8080
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7072.com:7072/eureka/,http://eureka7073.com:7073/eureka/,http://eureka7071.com:7071/eureka/
      
      
feign:
  hystrix: 
    enabled: true