server:
  port: 3344
spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:huangyuanhy/cloud-config.git  #github的仓库
          
          
          
          #http://localhost:3344/application-dev.yml  访问地址